server:
    port: 8080

aws:
    credentials:
        secret: vvuldbIZtbYfn62saztzS5fxtBqc/hsXb/mI+B+a
        id: AKIAIG7E4NOYSOHGVUVA

spring:
    profiles:
        active: dev

    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://52.7.93.102:3306/information_hub?autoConnect=true
        databaseName:
        serverName:
        username: root
        password: stagGOWL123
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    thymeleaf:
        mode: XHTML
        cache: false

search:
    host: 54.152.190.66

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2300
        prefix: gish

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M
